version: "3.6"

services:
  backend:
    image: icar-service-backend
    container_name: "icar-service-backend" 
    restart: always
    ports:
      - 3444:3000
    env_file:
      - /home/ubuntu/onest/icar-service-provider-backend/.env
